grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
    
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params: {}
    search_param_grid: {}

  module_1:
    class: Ridge
    module: sklearn.linear_model
    params:
      alpha: 1.0
    search_param_grid:
      alpha:
        - 0.1
        - 1.0
        - 10.0